name: Aria2 BT Downloader with 123Cloud Upload

# 允许手动触发工作流，并定义输入参数
on:
  workflow_dispatch:
    inputs:
      btLink:
        description: '磁力链接'
        required: true
        type: string
      aria2Args:
        description: 'aria2额外参数（如：--max-download-limit=10M）'
        required: false
        default: ''
        type: string
      proxy:
        description: '代理设置（如：http://proxy:port）'
        required: false
        default: ''
        type: string
      saveAsArtifact:
        description: '是否将下载文件保存为Artifact'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      uploadTo123Cloud:
        description: '是否上传到123云盘（半成品，暂不启用）'
        required: false
        default: 'false' 
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    name: Download BT with Aria2 and upload to 123Cloud
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install aria2 and python3
        run: |
          sudo apt update
          sudo apt install -y aria2
          aria2c --version
          sudo apt install -y python3 python3-pip
          python3 --version
          sudo apt install -y git
          git --version
      
      
      - name: Set up proxy if specified
        if: ${{ github.event.inputs.proxy != '' }}
        run: |
          echo "HTTP_PROXY=${{ github.event.inputs.proxy }}" >> $GITHUB_ENV
          echo "HTTPS_PROXY=${{ github.event.inputs.proxy }}" >> $GITHUB_ENV
      
      - name: Download with aria2
        run: |
          wget -P ${GITHUB_WORKSPACE} https://raw.githubusercontent.com/susulqx/GABTDL/refs/heads/main/aria2.conf
          wget -P ${GITHUB_WORKSPACE} https://raw.githubusercontent.com/susulqx/GABTDL/refs/heads/main/aria2.py
          wget -P ${GITHUB_WORKSPACE} https://raw.githubusercontent.com/P3TERX/aria2.conf/refs/heads/master/dht.dat
          wget -P ${GITHUB_WORKSPACE} https://raw.githubusercontent.com/P3TERX/aria2.conf/refs/heads/master/dht6.dat
          bash <(curl -fsSL git.io/tracker.sh) "${GITHUB_WORKSPACE}/aria2.conf"
          python ${GITHUB_WORKSPACE}/aria2.py --dir="${GITHUB_WORKSPACE}/BTDL" ${{ github.event.inputs.aria2Args }} --conf-path="${GITHUB_WORKSPACE}/aria2.conf" --dht-file-path ${GITHUB_WORKSPACE}/dht.dat --dht-file-pat6 ${GITHUB_WORKSPACE}/dht6.dat "${{ github.event.inputs.btLink }}"

      - name: List downloaded files
        run: |
          echo "下载目录内容:"
          ls -la "${GITHUB_WORKSPACE}/BTDL"
      
      - name: Upload artifact
        if: ${{ github.event.inputs.saveAsArtifact == 'true' }}
        uses: actions/upload-artifact@v4  
        with:
          name: bt-downloads
          path: "${GITHUB_WORKSPACE}/BTDL/**"
          if-no-files-found: warn
      
      - name: Upload to 123 Cloud
        if: ${{ github.event.inputs.uploadTo123Cloud == '半成品，暂不启用' }}
        env:
          CLOUD123_USERNAME: ${{ secrets.USERNAME }} 
          CLOUD123_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          # 安装123云盘上传工具
          mkdir 123Cloud
          git clone https://github.com/qq54288/123pan.git ${GITHUB_WORKSPACE}/123Cloud  # 直接克隆到目标目录，避免路径问题
          cd ${GITHUB_WORKSPACE}/123Cloud
          pip install -r requirements.txt
          # 注意：原脚本使用了expect语法但未安装expect，需要补充安装
          sudo apt install -y expect
          # 使用expect执行交互命令
          expect -c '
          set timeout 10
          spawn python android.py
          send "log\r"
          expect "*userName*"
          send "${{ secrets.USERNAME }}\r"
          expect "*passWord*"
          send "${{ secrets.PASSWORD }}\r"
          send "upload\r"
          expect "*文件路径*"
          send "\"${GITHUB_WORKSPACE}/BTDL\"\r"  # 修正了路径变量错误
          expect {
            "*同名文件*" {
              send "2\r"
            }
            timeout {
              
            }
          }
          '