name: Aria2 BT Downloader with 123Cloud Upload

# 允许手动触发工作流，并定义输入参数
on:
  workflow_dispatch:
    inputs:
      btLink:
        description: 'BT种子链接或磁力链接'
        required: true
        type: string
      outname:
        description: '下载文件名（不带后缀）'
        required: true
        type: string
      aria2Args:
        description: 'aria2额外参数（如：--max-download-limit=10M）'
        required: false
        default: ''
        type: string
      proxy:
        description: '代理设置（如：http://proxy:port）'
        required: false
        default: ''
        type: string
      saveAsArtifact:
        description: '是否将下载文件保存为Artifact'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      uploadTo123Cloud:
        description: '是否上传到123云盘'
        required: false
        default: false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    name: Download BT with Aria2 and upload to 123Cloud
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install aria2 and python3
        run: |
          sudo apt update
          sudo apt install -y aria2
          aria2c --version
          sudo apt install -y python3 python3-pip
          python3 --version
          sudo apt install -y git
          git --version
      
      - name: Create download directory
        run: mkdir -p ${{ github.event.inputs.downloadDir }}
      
      - name: Set up proxy if specified
        if: ${{ github.event.inputs.proxy != '' }}
        run: |
          echo "HTTP_PROXY=${{ github.event.inputs.proxy }}" >> $GITHUB_ENV
          echo "HTTPS_PROXY=${{ github.event.inputs.proxy }}" >> $GITHUB_ENV
      
      - name: Download with aria2
        run: |

          aria2c_cmd=(
          aria2c
          --dir="${GITHUB_WORKSPACE}/${{ github.event.inputs.outname }}"
          ${{ github.event.inputs.aria2Args }}
          "${{ github.event.inputs.btLink }}"
          -x "$(nproc --all)" -s "$(nproc --all)"
          )
          "${aria2c_cmd[@]}"
          
      
      - name: List downloaded files
        run: |
          echo "下载目录内容:"
          ls -la "${GITHUB_WORKSPACE}/${{ github.event.inputs.outname }}"
      
      - name: Upload as artifact
        if: ${{ github.event.inputs.saveAsArtifact == 'true' }}
        uses: actions/upload-artifact@v4  # 已将v3更新为v4，解决deprecated问题
        with:
          name: bt-downloads
          path: "${GITHUB_WORKSPACE}/${{ github.event.inputs.outname }}"
      
      - name: Upload to 123 Cloud
        if: ${{ github.event.inputs.uploadTo123Cloud == 'true' }}
        env:
          CLOUD123_USERNAME: ${{ secrets.USERNAME }} 
          CLOUD123_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          # 安装123云盘上传工具
          mkdir 123Cloud
          git clone https://github.com/qq54288/123pan.git ${GITHUB_WORKSPACE}/123Cloud  # 直接克隆到目标目录，避免路径问题
          cd ${GITHUB_WORKSPACE}/123Cloud
          pip install -r requirements.txt
          # 注意：原脚本使用了expect语法但未安装expect，需要补充安装
          sudo apt install -y expect
          # 使用expect执行交互命令
          expect -c '
          set timeout 10
          spawn python android.py
          send "log\r"
          expect "*userName*"
          send "${{ secrets.USERNAME }}\r"
          expect "*passWord*"
          send "${{ secrets.PASSWORD }}\r"
          send "upload\r"
          expect "*文件路径*"
          send "\"${{ github.event.inputs.downloadDir }}/${{ github.event.inputs.outname }}\"\r"
          expect {
            "*同名文件*" {
              send "2\r"
            }
            timeout {
        
            }
          }
          '
